apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: gspvsr/multibranch-flask-app:build-7
        ports:
        - containerPort: 5000
        